spring:
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP

spotify:
  client:
  redirect:
    uri: http://localhost:4000/auth/callback

server:
  port: 8888

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
#  global-config:
#    db-config:
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#      logic-delete-field: deleted

